# Copia este archivo y renómbralo a application.properties
# Reemplaza USUARIO y PASSWORD con tus credenciales de MongoDB Atlas

spring.application.name=gestion-tutorias-mongo
server.port=8081
spring.data.mongodb.uri=mongodb+srv://USUARIO:PASSWORD@cluster0.xxxxx.mongodb.net/gestion-tutorias?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=gestion-tutorias