spring.application.name=gestion-tutorias-mongo
server.port=8081
spring.data.mongodb.uri=mongodb+srv://aleja1106_db_user:K7iZY8TcTe37u12W@cluster0.ygfffef.mongodb.net/gestion-tutorias?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=gestion-tutorias